version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: car_rental_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_rental
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - car_rental_data:/var/lib/postgresql/data

volumes:
  car_rental_data:
